
services:
  namenode:
    build: ./Namenode
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870" # Web UI
      - "8020:8020" # IPC
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/hadoop-data/input
      - ./map_reduce:/hadoop-data/map_reduce
    networks:
      hadoop_network:
        aliases:
          - namenode

  datanode:
    build: ./Datanode
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864" # DataNode Web UI
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      hadoop_network:
        aliases:
          - datanode

  resourcemanager:
    build: ./Resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
    ports:
      - "8088:8088" # ResourceManager Web UI
    networks:
      hadoop_network:
        aliases:
          - resourcemanager

  nodemanager:
    build: ./Nodemanager
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - resourcemanager
      - datanode
    ports:
      - "8043:8043" # NodeManager Web UI
    networks:
      hadoop_network:
        aliases:
          - nodemanager

volumes:
  hadoop_namenode:
  hadoop_datanode:


networks:
  hadoop_network:
