version: "3"

services:
  namenode:
    build: ./Namenode
    hostname: 10.2.14.251
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data/:/hadoop-data/input
      - ./map_reduce/:/hadoop-data/map_reduce
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "8020:8020"
    networks:
      - hadoop_network

  resourcemanager:
    build: ./Resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    restart: on-failure
    depends_on:
      - namenode
      - datanode1
    ports:
      - "8089:8088"
    networks:
      - hadoop_network

  nodemanager1:
    build: ./Nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
    ports:
      - "8042:8042"
    networks:
      - hadoop_network
  # comenta esta linea

  nodemanager2:
    build: ./Nodemanager
    hostname: nodemanager2
    container_name: nodemanager2
    depends_on:
      - namenode
      - datanode1
    ports:
      - "8043:8042"
    networks:
      - hadoop_network

  datanode1:
    build: ./Datanode
    hostname: 10.2.14.251
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - hadoop_network

  # --------------------------------- AÑADIMOS DATANODES Y NODEMANAGER ---------------------------------
  datanode2:
    build: ./Datanode
    hostname: datanode2
    depends_on:
      - namenode
    ports:
      - "9865:9864"
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      - hadoop_network

  datanode3:
    build: ./Datanode
    hostname: datanode3
    depends_on:
      - namenode
    ports:
      - "9866:9864"
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
      - hadoop_network

  datanode4:
    build: ./Datanode
    hostname: datanode4
    depends_on:
      - namenode
    ports:
      - "9867:9864"
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
    networks:
      - hadoop_network

  datanode5:
    build: ./Datanode
    hostname: datanode5
    depends_on:
      - namenode
    ports:
      - "9868:9864"
    volumes:
      - hadoop_datanode5:/hadoop/dfs/data
    networks:
      - hadoop_network

# --------------------------------- VOLUMENES ---------------------------------

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  # ---- AÑADIMOS VOLUMENES ----
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:
  hadoop_datanode5:

networks:
  hadoop_network:
    name: hadoop_network
