services:
  namenode:
    build: ./Namenode
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870" # Web UI
      - "8020:8020" # IPC
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/hadoop-data/input
      - ./map_reduce:/hadoop-data/map_reduce
    networks:
      hadoop_network:
        aliases:
          - namenode

  resourcemanager:
    build: ./Resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
    ports:
      - "8088:8088" # ResourceManager Web UI
    networks:
      hadoop_network:
        aliases:
          - resourcemanager

  nodemanager:
    build: ./Nodemanager
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - resourcemanager
      - datanode
    ports:
      - "8043:8043" # NodeManager Web UI
    networks:
      hadoop_network:
        aliases:
          - nodemanager

  nodemanager2:
    build: ./Nodemanager
    container_name: nodemanager2
    hostname: nodemanager
    depends_on:
      - resourcemanager
      - datanode
    ports:
      - "8044:8043" # NodeManager Web UI
    networks:
      hadoop_network:
        aliases:
          - nodemanager2

  datanode:
    build: ./Datanode
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864" # DataNode Web UI
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      hadoop_network:
        aliases:
          - datanode

  # --------------------------------- AÑADIMOS DATANODES ---------------------------------
  datanode2:
    build: ./Datanode
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode
    ports:
      - "9865:9864" # DataNode Web UI
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      hadoop_network:
        aliases:
          - datanode2

  datanode3:
    build: ./Datanode
    container_name: datanode3
    hostname: datanode3
    depends_on:
      - namenode
    ports:
      - "9866:9864" # DataNode Web UI
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
      hadoop_network:
        aliases:
          - datanode3

  datanode4:
    build: ./Datanode
    container_name: datanode4
    hostname: datanode4
    depends_on:
      - namenode
    ports:
      - "9867:9864" # DataNode Web UI
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
    networks:
      hadoop_network:
        aliases:
          - datanode4

  datanode5:
    build: ./Datanode
    container_name: datanode5
    hostname: datanode5
    depends_on:
      - namenode
    ports:
      - "9868:9864" # DataNode Web UI
    volumes:
      - hadoop_datanode5:/hadoop/dfs/data
    networks:
      hadoop_network:
        aliases:
          - datanode5

# --------------------------------- VOLUMENES ---------------------------------

volumes:
  hadoop_namenode:
  hadoop_datanode:
  # ---- AÑADIMOS VOLUMENES ----
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:
  hadoop_datanode5:

networks:
  hadoop_network:
    name: hadoop_network
